
{% set data = load_setup_py_data() %}

package:
  name: ilastik-install
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - ilastik_install
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest tests
    - ilastik-install --help

about:
  home: TODO
  summary: Make ilastik binary relocatable
